# Generated by Django 4.1.4 on 2022-12-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "testapp",
            "0007_rename_quetion_question_rename_submition_submission_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="quetion",
            new_name="question",
        ),
    ]
